"""
The 10 built-in card templates.
Each has real layout differences (handled in public_card.html via
`layout` classes), not just a color swap.
"""

TEMPLATES = [
    {
        "slug": "minimal",
        "name": "Minimal",
        "layout": "centered",
        "primary_color": "#4F3FF0",
        "accent_color": "#FF6A45",
        "bg_color": "#FFFFFF",
        "text_color": "#12121A",
        "avatar_shape": "circle",
        "avatar_size": "md",
        "cover": False,
        "desc": "صورة في المنتصف، تصميم نظيف وهادئ.",
    },
    {
        "slug": "executive",
        "name": "Executive",
        "layout": "cover-hero",
        "primary_color": "#12121A",
        "accent_color": "#C9A24B",
        "bg_color": "#FFFFFF",
        "text_color": "#12121A",
        "avatar_shape": "circle",
        "avatar_size": "lg",
        "cover": True,
        "desc": "صورة كبيرة تغطي الرأس، طابع تنفيذي أنيق.",
    },
    {
        "slug": "corporate",
        "name": "Corporate",
        "layout": "side-profile",
        "primary_color": "#0B5CD5",
        "accent_color": "#00B8A9",
        "bg_color": "#F5F7FB",
        "text_color": "#111827",
        "avatar_shape": "rounded-square",
        "avatar_size": "md",
        "cover": False,
        "desc": "صورة جانبية بجانب المعلومات، طابع مؤسسي.",
    },
    {
        "slug": "luxury",
        "name": "Luxury",
        "layout": "dark-luxury",
        "primary_color": "#0E0E14",
        "accent_color": "#D4AF37",
        "bg_color": "#0E0E14",
        "text_color": "#F5F0E1",
        "avatar_shape": "circle",
        "avatar_size": "lg",
        "cover": False,
        "desc": "خلفية داكنة فاخرة بلمسة ذهبية.",
    },
    {
        "slug": "gradient",
        "name": "Gradient",
        "layout": "centered",
        "primary_color": "#7C3AED",
        "accent_color": "#FF5A87",
        "bg_color": "gradient-purple",
        "text_color": "#FFFFFF",
        "avatar_shape": "circle",
        "avatar_size": "md",
        "cover": False,
        "desc": "خلفية Gradient عصرية زاهية.",
    },
    {
        "slug": "glass",
        "name": "Glass",
        "layout": "glass",
        "primary_color": "#2563EB",
        "accent_color": "#22D3EE",
        "bg_color": "gradient-blue",
        "text_color": "#0B1220",
        "avatar_shape": "circle",
        "avatar_size": "md",
        "cover": False,
        "desc": "تأثير زجاجي شفاف Glassmorphism خفيف.",
    },
    {
        "slug": "creative",
        "name": "Creative",
        "layout": "asymmetric",
        "primary_color": "#FF6A45",
        "accent_color": "#12121A",
        "bg_color": "#FFF7F2",
        "text_color": "#12121A",
        "avatar_shape": "blob",
        "avatar_size": "lg",
        "cover": False,
        "desc": "تخطيط غير متماثل بروح إبداعية.",
    },
    {
        "slug": "dark",
        "name": "Dark",
        "layout": "centered",
        "primary_color": "#6D5DF6",
        "accent_color": "#00E0A4",
        "bg_color": "#0B0B14",
        "text_color": "#F2F2F7",
        "avatar_shape": "circle",
        "avatar_size": "md",
        "cover": False,
        "desc": "وضع داكن أنيق بلمسة نيون هادئة.",
    },
    {
        "slug": "elegant",
        "name": "Elegant",
        "layout": "side-profile",
        "primary_color": "#8B5E3C",
        "accent_color": "#C9A24B",
        "bg_color": "#FBF8F3",
        "text_color": "#2B2118",
        "avatar_shape": "circle",
        "avatar_size": "md",
        "cover": False,
        "desc": "ألوان ترابية دافئة وطباعة كلاسيكية أنيقة.",
    },
    {
        "slug": "professional",
        "name": "Professional",
        "layout": "cover-hero",
        "primary_color": "#0F766E",
        "accent_color": "#F59E0B",
        "bg_color": "#FFFFFF",
        "text_color": "#111827",
        "avatar_shape": "rounded-square",
        "avatar_size": "lg",
        "cover": True,
        "desc": "طابع احترافي متوازن يناسب جميع القطاعات.",
    },
]

TEMPLATES_BY_SLUG = {t["slug"]: t for t in TEMPLATES}

SECTION_LABELS = {
    "about": "About Me",
    "services": "Services",
    "social": "Social Links",
    "gallery": "Gallery",
    "contact": "Contact",
    "location": "Location",
    "experience": "Experience",
    "skills": "Skills",
    "testimonials": "Testimonials",
}

SOCIAL_PLATFORMS = [
    "facebook", "instagram", "linkedin", "x", "youtube",
    "tiktok", "github", "website", "whatsapp",
]
